AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Go-Gin using lambda-web-adapter container

Globals:
  Function:
    Timeout: 180

Resources:
  GinFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Events:
        APIEvent:
          Type: HttpApi
    Metadata:
      DockerTag: v1
      DockerContext: ./
      Dockerfile: Dockerfile

Outputs:
  GinApi:
    Description: 'API Gateway endpoint URL for Prod stage for Gin function'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
